"use client"
import { useState, useEffect } from "react"
import Link from "next/link"

const texts: Record<string, any> = {
  de: { title: "Impressum", provider: "Anbieter dieser Seite:", company: "PraxisOnline24", owner: "Housni Admy", street: "Berlinstraße 37", city: "55411 Bingen am Rhein", country: "Deutschland", email: "E-Mail: housniadmy@yahoo.de", phone: "Telefon: +49 (0) 6721 9875872", vat: "Umsatzsteuer-ID: (wird beantragt)", copyright: "Urheberrechtshinweis:", copyrightText: "Alle Inhalte dieser Website (Texte, Bilder, Layout) unterliegen dem Schutz des Urheberrechts.", odr: "EU-Streitbeilegung:", odrText: "Plattform der EU-Kommission:", noParticipation: "Wir nehmen nicht an Streitbeilegungsverfahren vor Verbraucherschlichtungsstellen teil.", liability: "Haftung für Inhalte:", liabilityText: "Die Inhalte wurden mit größter Sorgfalt erstellt. Wir übernehmen keine Gewähr für Richtigkeit und Aktualität.", linkLiability: "Haftung für Links:", linkLiabilityText: "Für Inhalte verlinkter Seiten sind ausschließlich deren Betreiber verantwortlich.", back: "← Zurück" },
  en: { title: "Imprint", provider: "Provider of this website:", company: "PraxisOnline24", owner: "Housni Admy", street: "Berlinstraße 37", city: "55411 Bingen am Rhein", country: "Germany", email: "Email: housniadmy@yahoo.de", phone: "Phone: +49 (0) 6721 9875872", vat: "VAT ID: (pending)", copyright: "Copyright Notice:", copyrightText: "All content on this website is protected by copyright.", odr: "EU Dispute Resolution:", odrText: "EU Commission platform:", noParticipation: "We do not participate in dispute resolution proceedings before consumer arbitration boards.", liability: "Liability for Content:", liabilityText: "Content created with utmost care. No guarantee for accuracy.", linkLiability: "Liability for Links:", linkLiabilityText: "We are not responsible for content on linked external websites.", back: "← Back" },
  fr: { title: "Mentions légales", provider: "Fournisseur du site:", company: "PraxisOnline24", owner: "Housni Admy", street: "Berlinstraße 37", city: "55411 Bingen am Rhein", country: "Allemagne", email: "E-mail: housniadmy@yahoo.de", phone: "Tél: +49 (0) 6721 9875872", vat: "TVA: (en cours)", copyright: "Droits d'auteur:", copyrightText: "Tout le contenu est protégé par le droit d'auteur.", odr: "Règlement des litiges UE:", odrText: "Plateforme de la Commission européenne:", noParticipation: "Nous ne participons pas aux procédures de règlement des litiges.", liability: "Responsabilité du contenu:", liabilityText: "Contenu créé avec soin. Pas de garantie d'exactitude.", linkLiability: "Responsabilité des liens:", linkLiabilityText: "Nous ne sommes pas responsables du contenu des sites liés.", back: "← Retour" },
  es: { title: "Aviso legal", provider: "Proveedor del sitio:", company: "PraxisOnline24", owner: "Housni Admy", street: "Berlinstraße 37", city: "55411 Bingen am Rhein", country: "Alemania", email: "Correo: housniadmy@yahoo.de", phone: "Tel: +49 (0) 6721 9875872", vat: "IVA: (pendiente)", copyright: "Derechos de autor:", copyrightText: "Todo el contenido está protegido por derechos de autor.", odr: "Resolución de litigios UE:", odrText: "Plataforma de la Comisión Europea:", noParticipation: "No participamos en procedimientos de arbitraje de consumo.", liability: "Responsabilidad del contenido:", liabilityText: "Contenido creado con cuidado. Sin garantía de exactitud.", linkLiability: "Responsabilidad de enlaces:", linkLiabilityText: "No somos responsables del contenido de sitios enlazados.", back: "← Volver" },
  it: { title: "Note legali", provider: "Fornitore del sito:", company: "PraxisOnline24", owner: "Housni Admy", street: "Berlinstraße 37", city: "55411 Bingen am Rhein", country: "Germania", email: "Email: housniadmy@yahoo.de", phone: "Tel: +49 (0) 6721 9875872", vat: "P.IVA: (in attesa)", copyright: "Diritto d'autore:", copyrightText: "Tutti i contenuti sono protetti da copyright.", odr: "Risoluzione controversie UE:", odrText: "Piattaforma della Commissione Europea:", noParticipation: "Non partecipiamo a procedure di arbitrato.", liability: "Responsabilità dei contenuti:", liabilityText: "Contenuti creati con cura. Nessuna garanzia.", linkLiability: "Responsabilità dei link:", linkLiabilityText: "Non siamo responsabili per contenuti di siti esterni.", back: "← Indietro" },
  pt: { title: "Aviso legal", provider: "Fornecedor do site:", company: "PraxisOnline24", owner: "Housni Admy", street: "Berlinstraße 37", city: "55411 Bingen am Rhein", country: "Alemanha", email: "E-mail: housniadmy@yahoo.de", phone: "Tel: +49 (0) 6721 9875872", vat: "NIF: (pendente)", copyright: "Direitos autorais:", copyrightText: "Todo o conteúdo é protegido por direitos autorais.", odr: "Resolução de litígios UE:", odrText: "Plataforma da Comissão Europeia:", noParticipation: "Não participamos em procedimentos de arbitragem.", liability: "Responsabilidade:", liabilityText: "Conteúdo criado com cuidado. Sem garantia.", linkLiability: "Responsabilidade dos links:", linkLiabilityText: "Não nos responsabilizamos por conteúdo externo.", back: "← Voltar" },
  nl: { title: "Colofon", provider: "Aanbieder:", company: "PraxisOnline24", owner: "Housni Admy", street: "Berlinstraße 37", city: "55411 Bingen am Rhein", country: "Duitsland", email: "E-mail: housniadmy@yahoo.de", phone: "Tel: +49 (0) 6721 9875872", vat: "BTW: (in aanvraag)", copyright: "Auteursrecht:", copyrightText: "Alle inhoud is auteursrechtelijk beschermd.", odr: "EU-geschillenbeslechting:", odrText: "Platform van de Europese Commissie:", noParticipation: "Wij nemen niet deel aan geschillenprocedures.", liability: "Aansprakelijkheid:", liabilityText: "Inhoud met zorg gemaakt. Geen garantie.", linkLiability: "Aansprakelijkheid links:", linkLiabilityText: "Wij zijn niet verantwoordelijk voor externe inhoud.", back: "← Terug" },
  pl: { title: "Nota prawna", provider: "Dostawca:", company: "PraxisOnline24", owner: "Housni Admy", street: "Berlinstraße 37", city: "55411 Bingen am Rhein", country: "Niemcy", email: "E-mail: housniadmy@yahoo.de", phone: "Tel: +49 (0) 6721 9875872", vat: "NIP: (w trakcie)", copyright: "Prawa autorskie:", copyrightText: "Cała zawartość chroniona prawem autorskim.", odr: "Rozstrzyganie sporów UE:", odrText: "Platforma Komisji Europejskiej:", noParticipation: "Nie uczestniczymy w postępowaniach arbitrażowych.", liability: "Odpowiedzialność:", liabilityText: "Treści tworzone starannie. Bez gwarancji.", linkLiability: "Odpowiedzialność za linki:", linkLiabilityText: "Nie odpowiadamy za treści zewnętrzne.", back: "← Wróć" },
  tr: { title: "Künye", provider: "Sağlayıcı:", company: "PraxisOnline24", owner: "Housni Admy", street: "Berlinstraße 37", city: "55411 Bingen am Rhein", country: "Almanya", email: "E-posta: housniadmy@yahoo.de", phone: "Tel: +49 (0) 6721 9875872", vat: "KDV: (beklemede)", copyright: "Telif Hakkı:", copyrightText: "Tüm içerik telif hakkıyla korunmaktadır.", odr: "AB Uyuşmazlık Çözümü:", odrText: "Avrupa Komisyonu platformu:", noParticipation: "Tüketici tahkim kurullarına katılmıyoruz.", liability: "İçerik Sorumluluğu:", liabilityText: "İçerik özenle oluşturulmuştur. Doğruluk garantisi yoktur.", linkLiability: "Bağlantı Sorumluluğu:", linkLiabilityText: "Harici sitelerin içeriğinden sorumlu değiliz.", back: "← Geri" },
  ja: { title: "法的情報", provider: "サイト提供者:", company: "PraxisOnline24", owner: "Housni Admy", street: "Berlinstraße 37", city: "55411 Bingen am Rhein", country: "ドイツ", email: "メール: housniadmy@yahoo.de", phone: "電話: +49 (0) 6721 9875872", vat: "VAT ID: (申請中)", copyright: "著作権:", copyrightText: "全コンテンツは著作権で保護されています。", odr: "EU紛争解決:", odrText: "欧州委員会プラットフォーム:", noParticipation: "消費者仲裁には参加していません。", liability: "コンテンツ責任:", liabilityText: "慎重に作成されていますが、正確性は保証されません。", linkLiability: "リンク責任:", linkLiabilityText: "外部サイトのコンテンツについて責任を負いません。", back: "← 戻る" },
  zh: { title: "法律声明", provider: "网站提供者:", company: "PraxisOnline24", owner: "Housni Admy", street: "Berlinstraße 37", city: "55411 Bingen am Rhein", country: "德国", email: "邮箱: housniadmy@yahoo.de", phone: "电话: +49 (0) 6721 9875872", vat: "增值税号: (待定)", copyright: "版权:", copyrightText: "所有内容受版权保护。", odr: "欧盟争议解决:", odrText: "欧盟委员会平台:", noParticipation: "我们不参与消费者仲裁。", liability: "内容责任:", liabilityText: "内容谨慎创建，不保证准确性。", linkLiability: "链接责任:", linkLiabilityText: "我们对外部链接内容不承担责任。", back: "← 返回" },
  cs: { title: "Impressum", provider: "Poskytovatel:", company: "PraxisOnline24", owner: "Housni Admy", street: "Berlinstraße 37", city: "55411 Bingen am Rhein", country: "Německo", email: "E-mail: housniadmy@yahoo.de", phone: "Tel: +49 (0) 6721 9875872", vat: "DIČ: (žádost podána)", copyright: "Autorská práva:", copyrightText: "Veškerý obsah je chráněn autorským právem.", odr: "Řešení sporů EU:", odrText: "Platforma Evropské komise:", noParticipation: "Neúčastníme se spotřebitelského arbitrážního řízení.", liability: "Odpovědnost:", liabilityText: "Obsah vytvořen s péčí. Bez záruky.", linkLiability: "Odpovědnost za odkazy:", linkLiabilityText: "Neodpovídáme za obsah externích stránek.", back: "← Zpět" },
  sk: { title: "Impressum", provider: "Poskytovateľ:", company: "PraxisOnline24", owner: "Housni Admy", street: "Berlinstraße 37", city: "55411 Bingen am Rhein", country: "Nemecko", email: "E-mail: housniadmy@yahoo.de", phone: "Tel: +49 (0) 6721 9875872", vat: "IČ DPH: (v žiadosti)", copyright: "Autorské práva:", copyrightText: "Všetok obsah je chránený autorským právom.", odr: "Riešenie sporov EÚ:", odrText: "Platforma Európskej komisie:", noParticipation: "Nezúčastňujeme sa spotrebiteľskej arbitráže.", liability: "Zodpovednosť:", liabilityText: "Obsah vytvorený s starostlivosťou. Bez záruky.", linkLiability: "Zodpovednosť za odkazy:", linkLiabilityText: "Nezodpovedáme za obsah externých stránok.", back: "← Späť" },
  sl: { title: "Impressum", provider: "Ponudnik:", company: "PraxisOnline24", owner: "Housni Admy", street: "Berlinstraße 37", city: "55411 Bingen am Rhein", country: "Nemčija", email: "E-pošta: housniadmy@yahoo.de", phone: "Tel: +49 (0) 6721 9875872", vat: "ID za DDV: (v obravnavi)", copyright: "Avtorske pravice:", copyrightText: "Vsa vsebina je zaščitena z avtorskimi pravicami.", odr: "Reševanje sporov EU:", odrText: "Platforma Evropske komisije:", noParticipation: "Ne sodelujemo v potrošniški arbitraži.", liability: "Odgovornost:", liabilityText: "Vsebina ustvarjena skrbno. Brez garancije.", linkLiability: "Odgovornost za povezave:", linkLiabilityText: "Ne odgovarjamo za vsebino zunanjih strani.", back: "← Nazaj" },
  sv: { title: "Impressum", provider: "Leverantör:", company: "PraxisOnline24", owner: "Housni Admy", street: "Berlinstraße 37", city: "55411 Bingen am Rhein", country: "Tyskland", email: "E-post: housniadmy@yahoo.de", phone: "Tel: +49 (0) 6721 9875872", vat: "Momsnr: (under behandling)", copyright: "Upphovsrätt:", copyrightText: "Allt innehåll skyddas av upphovsrätt.", odr: "EU-tvistlösning:", odrText: "EU-kommissionens plattform:", noParticipation: "Vi deltar inte i konsumenttvister.", liability: "Ansvar:", liabilityText: "Innehåll skapat med omsorg. Ingen garanti.", linkLiability: "Länkansvar:", linkLiabilityText: "Vi ansvarar inte för externt innehåll.", back: "← Tillbaka" },
  no: { title: "Impressum", provider: "Leverandør:", company: "PraxisOnline24", owner: "Housni Admy", street: "Berlinstraße 37", city: "55411 Bingen am Rhein", country: "Tyskland", email: "E-post: housniadmy@yahoo.de", phone: "Tlf: +49 (0) 6721 9875872", vat: "MVA: (under behandling)", copyright: "Opphavsrett:", copyrightText: "Alt innhold er opphavsrettslig beskyttet.", odr: "EU-tvisteløsning:", odrText: "EU-kommisjonens plattform:", noParticipation: "Vi deltar ikke i forbrukertvister.", liability: "Ansvar:", liabilityText: "Innhold laget med omhu. Ingen garanti.", linkLiability: "Lenkeansvar:", linkLiabilityText: "Vi er ikke ansvarlige for eksternt innhold.", back: "← Tilbake" },
  da: { title: "Impressum", provider: "Udbydere:", company: "PraxisOnline24", owner: "Housni Admy", street: "Berlinstraße 37", city: "55411 Bingen am Rhein", country: "Tyskland", email: "E-mail: housniadmy@yahoo.de", phone: "Tlf: +49 (0) 6721 9875872", vat: "Moms: (under behandling)", copyright: "Ophavsret:", copyrightText: "Alt indhold er ophavsretligt beskyttet.", odr: "EU-tvistbilæggelse:", odrText: "EU-Kommissionens platform:", noParticipation: "Vi deltager ikke i forbrugertvister.", liability: "Ansvar:", liabilityText: "Indhold lavet med omhu. Ingen garanti.", linkLiability: "Linkansvar:", linkLiabilityText: "Vi er ikke ansvarlige for eksternt indhold.", back: "← Tilbage" },
}

export default function Impressum() {
  const [lang, setLang] = useState("de")
  useEffect(() => {
    const p = new URLSearchParams(window.location.search)
    const ul = p.get("setLang")
    const stored = ul || localStorage.getItem("lang")
    if (stored && texts[stored]) setLang(stored)
    else setLang("en")
  }, [])
  const t = texts[lang] || texts.en

  return (
    <main className="min-h-screen bg-gradient-to-b from-blue-50 to-white p-4 sm:p-8 max-w-3xl mx-auto">
      <div className="bg-white border border-blue-200 shadow-sm rounded-xl p-6 sm:p-10">
        <h1 className="text-2xl sm:text-4xl font-bold mb-6 sm:mb-8 text-gray-900">{t.title}</h1>
        <div className="space-y-4 text-sm sm:text-base text-gray-700">
          <p><strong>{t.provider}</strong></p>
          <p>{t.company}</p><p>{t.owner}</p><p>{t.street}</p><p>{t.city}</p><p>{t.country}</p>
          <p className="mt-2">{t.email}</p><p>{t.phone}</p>
          <p className="mt-4"><strong>{t.vat}</strong></p>
          <p className="mt-4"><strong>{t.copyright}</strong> {t.copyrightText}</p>
          <p><strong>{t.odr}</strong> {t.odrText} <a href="https://ec.europa.eu/consumers/odr" target="_blank" className="underline text-[#3B82F6]">https://ec.europa.eu/consumers/odr</a></p>
          <p>{t.noParticipation}</p>
          <p className="mt-4"><strong>{t.liability}</strong> {t.liabilityText}</p>
          <p><strong>{t.linkLiability}</strong> {t.linkLiabilityText}</p>
        </div>
      </div>
      <div className="mt-6 text-center"><Link href="/" className="text-[#3B82F6] hover:text-blue-600 underline text-base sm:text-lg">{t.back}</Link></div>
    </main>
  )
}
