export const translations: Record<string, Record<string, string>> = {
  de: { home: "Startseite", login: "Anmelden", register: "Registrieren", switchLang: "Sprache", hero: "Weniger Telefonate. Mehr Zeit für Patienten.", subtitle: "Automatisieren Sie Terminbuchung, Erinnerungen und Patientenkommunikation.", start: "Kostenlos starten", feat1title: "Online-Terminbuchung", feat1desc: "Reduziert Telefonanrufe um bis zu 40%.", feat2title: "Erinnerungen", feat2desc: "Spart bis zu 5 Stunden pro Woche.", feat3title: "Bewertungen", feat3desc: "Unterstützt Praxen beim Bewertungsmanagement.", prices: "Preise", basic: "Basic", pro: "Pro", business: "Business", perMonth: "/Monat", basic1: "Online-Terminbuchung", basic2: "E-Mail-Erinnerungen", basic3: "Für kleine Praxen", pro1: "Alles aus Basic", pro2: "Bewertungssteuerung", pro3: "Für wachsende Praxen", bus1: "Alles aus Pro", bus2: "Storno + Warteliste", bus3: "Für größere Praxen", anamnese: "Anamnese-Bogen", anamneseDesc: "Patienten-Fragebogen online", erezept: "E-Rezept", erezeptDesc: "Medikamenten-Erinnerung", statistiken: "Statistiken", statistikenDesc: "Patientenzahlen & Umsatz", howTitle: "So einfach funktioniert's", howSub: "In 4 Schritten zur automatisierten Praxis", step1: "Terminbuchung", step1Desc: "Patient bucht online", step2: "Bestätigung", step2Desc: "Automatische E-Mail/SMS", step3: "Stornierung", step3Desc: "Patient kann absagen", step4: "Nachrücken", step4Desc: "Warteliste rückt nach" },
  en: { home: "Home", login: "Login", register: "Register", switchLang: "Language", hero: "Less phone calls. More time for patients.", subtitle: "Automate appointment booking, reminders and patient communication.", start: "Start free", feat1title: "Online Booking", feat1desc: "Reduces phone calls by up to 40%.", feat2title: "Reminders", feat2desc: "Saves up to 5 hours per week.", feat3title: "Reviews", feat3desc: "Supports practices with review management.", prices: "Pricing", basic: "Basic", pro: "Pro", business: "Business", perMonth: "/month", basic1: "Online Booking", basic2: "Email Reminders", basic3: "For small practices", pro1: "Everything from Basic", pro2: "Review Management", pro3: "For growing practices", bus1: "Everything from Pro", bus2: "Cancellation + waitlist", bus3: "For larger practices", anamnese: "Medical History", anamneseDesc: "Online patient questionnaire", erezept: "E-Prescription", erezeptDesc: "Medication reminder", statistiken: "Statistics", statistikenDesc: "Patient numbers & revenue", howTitle: "How it works", howSub: "In 4 steps to your automated practice", step1: "Booking", step1Desc: "Patient books online", step2: "Confirmation", step2Desc: "Automatic email/SMS", step3: "Cancellation", step3Desc: "Patient can cancel", step4: "Move up", step4Desc: "Waiting list moves up" },
  fr: { home: "Accueil", login: "Connexion", register: "S'inscrire", switchLang: "Langue", hero: "Moins d'appels. Plus de temps pour les patients.", subtitle: "Automatisez la prise de rendez-vous, les rappels et la communication.", start: "Démarrer gratuitement", feat1title: "Rendez-vous en ligne", feat1desc: "Réduit les appels téléphoniques jusqu'à 40%.", feat2title: "Rappels", feat2desc: "Économise jusqu'à 5 heures par semaine.", feat3title: "Avis", feat3desc: "Gestion des avis pour les cabinets.", prices: "Tarifs", basic: "Basique", pro: "Professionnel", business: "Entreprise", perMonth: "/mois", basic1: "Rendez-vous en ligne", basic2: "Rappels email", basic3: "Pour petits cabinets", pro1: "Tout de Basique", pro2: "Gestion des avis", pro3: "Pour cabinets en croissance", bus1: "Tout de Pro", bus2: "Annulation + liste d'attente", bus3: "Pour grands cabinets", anamnese: "Anamnèse", anamneseDesc: "Questionnaire patient en ligne", erezept: "E-Ordonnance", erezeptDesc: "Rappel médicament", statistiken: "Statistiques", statistikenDesc: "Patients & revenus", howTitle: "Comment ça fonctionne", howSub: "En 4 étapes vers votre cabinet automatisé", step1: "Réservation", step1Desc: "Patient réserve en ligne", step2: "Confirmation", step2Desc: "Email/SMS automatique", step3: "Annulation", step3Desc: "Le patient peut annuler", step4: "Liste d'attente", step4Desc: "La liste d'attente avance" },
  es: { home: "Inicio", login: "Iniciar sesión", register: "Registrarse", switchLang: "Idioma", hero: "Menos llamadas. Más tiempo para los pacientes.", subtitle: "Automatice reservas, recordatorios y comunicación.", start: "Comenzar gratis", feat1title: "Reservas online", feat1desc: "Reduce llamadas hasta un 40%.", feat2title: "Recordatorios", feat2desc: "Ahorra hasta 5 horas por semana.", feat3title: "Opiniones", feat3desc: "Gestión de opiniones para consultorios.", prices: "Precios", basic: "Básico", pro: "Profesional", business: "Empresa", perMonth: "/mes", basic1: "Reservas online", basic2: "Recordatorios email", basic3: "Para pequeños consultorios", pro1: "Todo de Básico", pro2: "Gestión de opiniones", pro3: "Para consultorios en crecimiento", bus1: "Todo de Pro", bus2: "Cancelación + lista de espera", bus3: "Para grandes consultorios", anamnese: "Anamnesis", anamneseDesc: "Cuestionario online", erezept: "E-Receta", erezeptDesc: "Recordatorio medicación", statistiken: "Estadísticas", statistikenDesc: "Pacientes & ingresos", howTitle: "Cómo funciona", howSub: "En 4 pasos hacia su consultorio automatizado", step1: "Reserva", step1Desc: "Paciente reserva online", step2: "Confirmación", step2Desc: "Email/SMS automático", step3: "Cancelación", step3Desc: "El paciente puede cancelar", step4: "Lista de espera", step4Desc: "La lista de espera avanza" },
  it: { home: "Home", login: "Accedi", register: "Registrati", switchLang: "Lingua", hero: "Meno chiamate. Più tempo per i pazienti.", subtitle: "Automatizza prenotazioni, promemoria e comunicazione.", start: "Inizia gratis", feat1title: "Prenotazioni online", feat1desc: "Riduce le chiamate fino al 40%.", feat2title: "Promemoria", feat2desc: "Risparmia fino a 5 ore a settimana.", feat3title: "Recensioni", feat3desc: "Gestione recensioni per studi medici.", prices: "Prezzi", basic: "Base", pro: "Professionale", business: "Azienda", perMonth: "/mese", basic1: "Prenotazioni online", basic2: "Promemoria email", basic3: "Per piccoli studi", pro1: "Tutto di Base", pro2: "Gestione recensioni", pro3: "Per studi in crescita", bus1: "Tutto di Pro", bus2: "Cancellazione + lista d'attesa", bus3: "Per grandi studi", anamnese: "Anamnesi", anamneseDesc: "Questionario online", erezept: "E-Ricetta", erezeptDesc: "Promemoria farmaci", statistiken: "Statistiche", statistikenDesc: "Pazienti & ricavi", howTitle: "Come funziona", howSub: "In 4 passi verso il tuo studio automatizzato", step1: "Prenotazione", step1Desc: "Paziente prenota online", step2: "Conferma", step2Desc: "Email/SMS automatico", step3: "Cancellazione", step3Desc: "Il paziente può cancellare", step4: "Lista d'attesa", step4Desc: "La lista d'attesa avanza" },
  pt: { home: "Início", login: "Entrar", register: "Registar", switchLang: "Idioma", hero: "Menos chamadas. Mais tempo para os pacientes.", subtitle: "Automatize agendamentos, lembretes e comunicação.", start: "Começar grátis", feat1title: "Agendamento online", feat1desc: "Reduz chamadas em até 40%.", feat2title: "Lembretes", feat2desc: "Economiza até 5 horas por semana.", feat3title: "Avaliações", feat3desc: "Gestão de avaliações para clínicas.", prices: "Preços", basic: "Básico", pro: "Profissional", business: "Empresa", perMonth: "/mês", basic1: "Agendamento online", basic2: "Lembretes email", basic3: "Para pequenas clínicas", pro1: "Tudo do Básico", pro2: "Gestão de avaliações", pro3: "Para clínicas em crescimento", bus1: "Tudo do Pro", bus2: "Cancelamento + lista de espera", bus3: "Para grandes clínicas", anamnese: "Anamnese", anamneseDesc: "Questionário online", erezept: "E-Receita", erezeptDesc: "Lembrete medicação", statistiken: "Estatísticas", statistikenDesc: "Pacientes & receita", howTitle: "Como funciona", howSub: "Em 4 passos para sua clínica automatizada", step1: "Agendamento", step1Desc: "Paciente agenda online", step2: "Confirmação", step2Desc: "Email/SMS automático", step3: "Cancelamento", step3Desc: "Paciente pode cancelar", step4: "Lista de espera", step4Desc: "Lista de espera avança" },
  nl: { home: "Home", login: "Inloggen", register: "Registreren", switchLang: "Taal", hero: "Minder telefoontjes. Meer tijd voor patiënten.", subtitle: "Automatiseer afspraken, herinneringen en communicatie.", start: "Gratis starten", feat1title: "Online afspraken", feat1desc: "Vermindert telefoontjes tot 40%.", feat2title: "Herinneringen", feat2desc: "Bespaart tot 5 uur per week.", feat3title: "Beoordelingen", feat3desc: "Ondersteunt praktijken met beoordelingsbeheer.", prices: "Prijzen", basic: "Basis", pro: "Professioneel", business: "Zakelijk", perMonth: "/maand", basic1: "Online afspraken", basic2: "Email herinneringen", basic3: "Voor kleine praktijken", pro1: "Alles van Basis", pro2: "Beoordelingsbeheer", pro3: "Voor groeiende praktijken", bus1: "Alles van Pro", bus2: "Annulering + wachtlijst", bus3: "Voor grote praktijken", anamnese: "Anamnese", anamneseDesc: "Online vragenlijst", erezept: "E-Recept", erezeptDesc: "Medicijnherinnering", statistiken: "Statistieken", statistikenDesc: "Patiënten & omzet", howTitle: "Hoe het werkt", howSub: "In 4 stappen naar uw geautomatiseerde praktijk", step1: "Boeking", step1Desc: "Patiënt boekt online", step2: "Bevestiging", step2Desc: "Automatische email/SMS", step3: "Annulering", step3Desc: "Patiënt kan annuleren", step4: "Wachtlijst", step4Desc: "Wachtlijst schuift door" },
  pl: { home: "Strona główna", login: "Zaloguj", register: "Zarejestruj", switchLang: "Język", hero: "Mniej telefonów. Więcej czasu dla pacjentów.", subtitle: "Automatyzuj rezerwacje, przypomnienia i komunikację.", start: "Zacznij za darmo", feat1title: "Rezerwacje online", feat1desc: "Zmniejsza liczbę telefonów o 40%.", feat2title: "Przypomnienia", feat2desc: "Oszczędza do 5 godzin tygodniowo.", feat3title: "Opinie", feat3desc: "Wspomaga zarządzanie opiniami w praktykach.", prices: "Ceny", basic: "Podstawowy", pro: "Profesjonalny", business: "Biznes", perMonth: "/miesiąc", basic1: "Rezerwacje online", basic2: "Przypomnienia email", basic3: "Dla małych praktyk", pro1: "Wszystko z Podstawowego", pro2: "Zarządzanie opiniami", pro3: "Dla rozwijających się praktyk", bus1: "Wszystko z Pro", bus2: "Anulowanie + lista oczekujących", bus3: "Dla dużych praktyk", anamnese: "Anamneza", anamneseDesc: "Kwestionariusz online", erezept: "E-Recepta", erezeptDesc: "Przypomnienie o lekach", statistiken: "Statystyki", statistikenDesc: "Pacjenci & przychód", howTitle: "Jak to działa", howSub: "W 4 krokach do zautomatyzowanej praktyki", step1: "Rezerwacja", step1Desc: "Pacjent rezerwuje online", step2: "Potwierdzenie", step2Desc: "Automatyczny email/SMS", step3: "Anulowanie", step3Desc: "Pacjent może anulować", step4: "Lista oczekujących", step4Desc: "Lista oczekujących przesuwa się" },
  tr: { home: "Ana Sayfa", login: "Giriş", register: "Kayıt", switchLang: "Dil", hero: "Daha az telefon. Hastalar için daha fazla zaman.", subtitle: "Randevu alma, hatırlatmalar ve iletişimi otomatikleştirin.", start: "Ücretsiz başla", feat1title: "Online Randevu", feat1desc: "Telefonları %40'a kadar azaltır.", feat2title: "Hatırlatmalar", feat2desc: "Haftada 5 saate kadar tasarruf sağlar.", feat3title: "Değerlendirmeler", feat3desc: "Pratiklerin değerlendirme yönetimini destekler.", prices: "Fiyatlar", basic: "Temel", pro: "Profesyonel", business: "Kurumsal", perMonth: "/ay", basic1: "Online Randevu", basic2: "Email Hatırlatmalar", basic3: "Küçük pratikler için", pro1: "Temel'deki her şey", pro2: "Değerlendirme Yönetimi", pro3: "Büyüyen pratikler için", bus1: "Pro'daki her şey", bus2: "İptal + bekleme listesi", bus3: "Büyük pratikler için", anamnese: "Anamnez", anamneseDesc: "Online hasta formu", erezept: "E-Reçete", erezeptDesc: "İlaç hatırlatma", statistiken: "İstatistikler", statistikenDesc: "Hasta sayıları & gelir", howTitle: "Nasıl çalışır", howSub: "Otomatik pratiğinize 4 adımda", step1: "Randevu", step1Desc: "Hasta online randevu alır", step2: "Onay", step2Desc: "Otomatik email/SMS", step3: "İptal", step3Desc: "Hasta iptal edebilir", step4: "Bekleme listesi", step4Desc: "Bekleme listesi ilerler" },
}

export const languages = [
  { code: "de", name: "Deutsch", label: "Deutsch" },
  { code: "en", name: "English", label: "English" },
  { code: "fr", name: "Français", label: "Français" },
  { code: "es", name: "Español", label: "Español" },
  { code: "it", name: "Italiano", label: "Italiano" },
  { code: "pt", name: "Português", label: "Português" },
  { code: "nl", name: "Nederlands", label: "Nederlands" },
  { code: "pl", name: "Polski", label: "Polski" },
  { code: "tr", name: "Türkçe", label: "Türkçe" },
]

export function detectLanguage(): string {
  if (typeof navigator === "undefined") return "de"
  const browserLang = navigator.language.split("-")[0]
  return languages.some(lang => lang.code === browserLang) ? browserLang : "de"
}