export const trustTexts: Record<string, any> = {
  de: { title: "Ihre Daten sind sicher", d1: "DSGVO-konform", d2: "EU-Server", d3: "Verschlüsselt", d4: "Kein Datenverkauf" },
  en: { title: "Your Data is Safe", d1: "GDPR Compliant", d2: "EU Servers", d3: "Encrypted", d4: "No Data Sales" },
  fr: { title: "Vos données sont en sécurité", d1: "Conforme RGPD", d2: "Serveurs UE", d3: "Crypté", d4: "Pas de vente" },
  es: { title: "Sus datos están seguros", d1: "Cumple RGPD", d2: "Servidores UE", d3: "Encriptado", d4: "Sin venta" },
  it: { title: "I tuoi dati sono al sicuro", d1: "Conforme GDPR", d2: "Server UE", d3: "Crittografato", d4: "Nessuna vendita" },
  pt: { title: "Seus dados estão seguros", d1: "Conforme RGPD", d2: "Servidores UE", d3: "Criptografado", d4: "Sem venda" },
  nl: { title: "Uw gegevens zijn veilig", d1: "AVG-conform", d2: "EU-servers", d3: "Versleuteld", d4: "Geen verkoop" },
  pl: { title: "Twoje dane są bezpieczne", d1: "Zgodne z RODO", d2: "Serwery UE", d3: "Szyfrowane", d4: "Bez sprzedaży" },
  tr: { title: "Verileriniz güvende", d1: "GDPR uyumlu", d2: "AB sunucuları", d3: "Şifreli", d4: "Satış yok" },
  ja: { title: "データは安全です", d1: "GDPR準拠", d2: "EUサーバー", d3: "暗号化", d4: "データ販売なし" },
  zh: { title: "您的数据是安全的", d1: "符合GDPR", d2: "欧盟服务器", d3: "加密", d4: "无数据出售" },
  cs: { title: "Vaše data jsou v bezpečí", d1: "GDPR", d2: "EU servery", d3: "Šifrované", d4: "Žádný prodej" },
  sk: { title: "Vaše dáta sú v bezpečí", d1: "GDPR", d2: "EU servery", d3: "Šifrované", d4: "Žiadny predaj" },
  sl: { title: "Vaši podatki so varni", d1: "GDPR", d2: "EU strežniki", d3: "Šifrirano", d4: "Brez prodaje" },
  sv: { title: "Dina data är säkra", d1: "GDPR", d2: "EU-servrar", d3: "Krypterat", d4: "Ingen försäljning" },
  no: { title: "Dine data er trygge", d1: "GDPR", d2: "EU-servere", d3: "Kryptert", d4: "Ingen salg" },
  da: { title: "Dine data er sikre", d1: "GDPR", d2: "EU-servere", d3: "Krypteret", d4: "Intet salg" },
}

export const demoTexts: Record<string, any> = {
  de: { title: "Sehen Sie PraxisOnline24 in Aktion", desc: "In 2 Minuten erfahren Sie, wie PraxisOnline24 Ihrer Praxis hilft.", btn: "Demo ansehen", cta: "Praxis testen", badge: "Empfohlen" },
  en: { title: "See PraxisOnline24 in Action", desc: "Learn in 2 minutes how PraxisOnline24 helps your practice.", btn: "Watch Demo", cta: "Try Practice", badge: "Recommended" },
  fr: { title: "Voyez PraxisOnline24 en action", desc: "Découvrez en 2 minutes comment PraxisOnline24 aide votre cabinet.", btn: "Voir la démo", cta: "Commencer gratuitement", badge: "Recommandé" },
  es: { title: "Vea PraxisOnline24 en acción", desc: "Descubra en 2 minutos cómo PraxisOnline24 ayuda a su consulta.", btn: "Ver demo", cta: "Comenzar gratis", badge: "Recomendado" },
  it: { title: "Vedi PraxisOnline24 in azione", desc: "Scopri in 2 minuti come PraxisOnline24 aiuta il tuo studio.", btn: "Guarda demo", cta: "Inizia gratuitamente", badge: "Consigliato" },
  pt: { title: "Veja o PraxisOnline24 em ação", desc: "Descubra em 2 minutos como o PraxisOnline24 ajuda seu consultório.", btn: "Ver demo", cta: "Começar gratuitamente", badge: "Recomendado" },
  nl: { title: "Zie PraxisOnline24 in actie", desc: "Ontdek in 2 minuten hoe PraxisOnline24 uw praktijk helpt.", btn: "Bekijk demo", cta: "Gratis starten", badge: "Aanbevolen" },
  pl: { title: "Zobacz PraxisOnline24 w akcji", desc: "Dowiedz się w 2 minuty, jak PraxisOnline24 pomaga Twojemu gabinetowi.", btn: "Obejrzyj demo", cta: "Zacznij za darmo", badge: "Polecany" },
  tr: { title: "PraxisOnline24'ı iş başında görün", desc: "PraxisOnline24'ın muayenehanenize nasıl yardımcı olduğunu 2 dakikada öğrenin.", btn: "Demo izle", cta: "Ücretsiz başla", badge: "Önerilen" },
  ja: { title: "PraxisOnline24の動作を見る", desc: "2分でPraxisOnline24が医院にどのように役立つかをご覧ください。", btn: "デモを見る", cta: "無料で始める", badge: "推奨" },
  zh: { title: "观看PraxisOnline24的实际操作", desc: "在2分钟内了解PraxisOnline24如何帮助您的诊所。", btn: "观看演示", cta: "免费开始", badge: "推荐" },
  cs: { title: "Podívejte se na PraxisOnline24 v akci", desc: "Za 2 minuty zjistíte, jak PraxisOnline24 pomáhá vaší ordinaci.", btn: "Demo", cta: "Začít zdarma", badge: "Doporučeno" },
  sk: { title: "Pozrite si PraxisOnline24 v akcii", desc: "Za 2 minúty zistíte, ako PraxisOnline24 pomáha vašej ordinácii.", btn: "Demo", cta: "Začať zadarmo", badge: "Odporúčané" },
  sl: { title: "Oglejte si PraxisOnline24 v akciji", desc: "V 2 minutah izveste, kako PraxisOnline24 pomaga vaši ordinaciji.", btn: "Demo", cta: "Začni brezplačno", badge: "Priporočeno" },
  sv: { title: "Se PraxisOnline24 i aktion", desc: "Lär dig på 2 minuter hur PraxisOnline24 hjälper din mottagning.", btn: "Demo", cta: "Inizia gratuitamente", badge: "Rekommenderas" },
  no: { title: "Se PraxisOnline24 i aksjon", desc: "Lær på 2 minutter hvordan PraxisOnline24 hjelper din praksis.", btn: "Demo", cta: "Start gratis", badge: "Anbefalt" },
  da: { title: "Se PraxisOnline24 i aktion", desc: "Lær på 2 minutter, hvordan PraxisOnline24 hjælper din praksis.", btn: "Demo", cta: "Start gratis", badge: "Anbefalet" },
}
