"use client"
import { useState, useEffect } from "react"
import Link from "next/link"

const texts: Record<string, any> = {
  de: { title: "Datenschutzerklärung", h1: "1. Verantwortlicher", h2: "2. Datenerfassung", h3: "3. Ihre Rechte", h4: "4. Hosting", h5: "5. Cookies", h6: "6. Rechtsgrundlage", resp: "Verantwortlich: PraxisOnline, Berlinstraße 37, 55411 Bingen am Rhein, Deutschland. info@praxisonline24.com", rights: "Recht auf Auskunft, Berichtigung, Löschung, Einschränkung, Datenübertragbarkeit, Widerspruch (Art. 15-21 DSGVO).", law: "DSGVO und BDSG.", land: "Deutschland", back: "← Zurück", data: "Name (optional), E-Mail, Passwort (verschlüsselt). Zahlungen über Stripe (keine Speicherung auf unseren Servern).", hosting: "Vercel (USA, EU-Standardvertragsklauseln), Supabase (EU-Server), Brevo (Frankreich), Tawk.to (Standardvertragsklauseln).", cookies: "Nur technisch notwendige Cookies. Keine Tracking-Cookies." },
  en: { title: "Privacy Policy", h1: "1. Data Controller", h2: "2. Data Collection", h3: "3. Your Rights", h4: "4. Hosting", h5: "5. Cookies", h6: "6. Legal Basis", resp: "Responsible: PraxisOnline24, Berlinstraße 37, 55411 Bingen am Rhein, Germany. info@praxisonline24.com", rights: "Right to access, rectification, erasure, restriction, portability, objection (Art. 15-21 GDPR).", law: "GDPR / UK DPA 2018.", land: "International", back: "← Back", data: "Name (optional), email, password (encrypted). Payments via Stripe (not stored on our servers).", hosting: "Vercel (USA, EU Standard Contractual Clauses), Supabase (EU servers), Brevo (France), Tawk.to (SCC).", cookies: "Only technically necessary cookies. No tracking cookies." },
  fr: { title: "Politique de confidentialité", h1: "1. Responsable", h2: "2. Collecte de données", h3: "3. Vos droits", h4: "4. Hébergement", h5: "5. Cookies", h6: "6. Base juridique", resp: "Responsable: PraxisOnline, Berlinstraße 37, 55411 Bingen am Rhein, Allemagne. info@praxisonline.com", rights: "Droit d'accès, rectification, effacement, limitation, portabilité, opposition (Art. 15-21 RGPD).", law: "RGPD et Loi Informatique et Libertés.", land: "France", back: "← Retour", data: "Nom (optionnel), email, mot de passe (crypté). Paiements via Stripe.", hosting: "Vercel (USA, clauses contractuelles types UE), Supabase (serveurs UE), Brevo (France), Tawk.to.", cookies: "Uniquement des cookies techniquement nécessaires." },
  es: { title: "Política de privacidad", h1: "1. Responsable", h2: "2. Recogida de datos", h3: "3. Sus derechos", h4: "4. Alojamiento", h5: "5. Cookies", h6: "6. Base jurídica", resp: "Responsable: PraxisOnline, Berlinstraße 37, 55411 Bingen am Rhein, Alemania. info@praxisonline.com", rights: "Derecho de acceso, rectificación, supresión, limitación, portabilidad, oposición (Art. 15-21 RGPD).", law: "RGPD y LOPDGDD.", land: "España", back: "← Volver", data: "Nombre (opcional), email, contraseña (cifrada). Pagos a través de Stripe.", hosting: "Vercel (EE.UU., cláusulas contractuales tipo UE), Supabase (servidores UE), Brevo (Francia), Tawk.to.", cookies: "Solo cookies técnicamente necesarias." },
  it: { title: "Informativa sulla privacy", h1: "1. Responsabile", h2: "2. Raccolta dati", h3: "3. I tuoi diritti", h4: "4. Hosting", h5: "5. Cookie", h6: "6. Base giuridica", resp: "Responsabile: PraxisOnline, Berlinstraße 37, 55411 Bingen am Rhein, Germania. info@praxisonline.com", rights: "Diritto di accesso, rettifica, cancellazione, limitazione, portabilità, opposizione (Art. 15-21 GDPR).", law: "GDPR e D.Lgs. 196/2003.", land: "Italia", back: "← Indietro", data: "Nome (opzionale), email, password (crittografata). Pagamenti tramite Stripe.", hosting: "Vercel (USA, clausole contrattuali standard UE), Supabase (server UE), Brevo (Francia), Tawk.to.", cookies: "Solo cookie tecnicamente necessari." },
  pt: { title: "Política de Privacidade", h1: "1. Responsável", h2: "2. Coleta de dados", h3: "3. Seus direitos", h4: "4. Hospedagem", h5: "5. Cookies", h6: "6. Base jurídica", resp: "Responsável: PraxisOnline, Berlinstraße 37, 55411 Bingen am Rhein, Alemanha. info@praxisonline.com", rights: "Direito de acesso, retificação, eliminação, limitação, portabilidade, oposição (Art. 15-21 RGPD).", law: "RGPD / LGPD (Brasil).", land: "Portugal / Brasil", back: "← Voltar", data: "Nome (opcional), email, senha (criptografada). Pagamentos via Stripe.", hosting: "Vercel (EUA, cláusulas contratuais-tipo UE), Supabase (servidores UE), Brevo (França), Tawk.to.", cookies: "Apenas cookies tecnicamente necessários." },
  nl: { title: "Privacyverklaring", h1: "1. Verantwoordelijke", h2: "2. Gegevensverzameling", h3: "3. Uw rechten", h4: "4. Hosting", h5: "5. Cookies", h6: "6. Juridische basis", resp: "Verantwoordelijke: PraxisOnline, Berlinstraße 37, 55411 Bingen am Rhein, Duitsland. info@praxisonline.com", rights: "Recht op inzage, rectificatie, wissing, beperking, overdraagbaarheid, bezwaar (Art. 15-21 AVG).", law: "AVG en UAVG.", land: "Nederland", back: "← Terug", data: "Naam (optioneel), e-mail, wachtwoord (versleuteld). Betalingen via Stripe.", hosting: "Vercel (VS, EU-modelcontractbepalingen), Supabase (EU-servers), Brevo (Frankrijk), Tawk.to.", cookies: "Alleen technisch noodzakelijke cookies." },
  pl: { title: "Polityka prywatności", h1: "1. Administrator", h2: "2. Gromadzenie danych", h3: "3. Twoje prawa", h4: "4. Hosting", h5: "5. Pliki cookie", h6: "6. Podstawa prawna", resp: "Administrator: PraxisOnline, Berlinstraße 37, 55411 Bingen am Rhein, Niemcy. info@praxisonline.com", rights: "Prawo dostępu, sprostowania, usunięcia, ograniczenia, przenoszenia, sprzeciwu (Art. 15-21 RODO).", law: "RODO i ustawa o ochronie danych.", land: "Polska", back: "← Wróć", data: "Imię (opcjonalnie), e-mail, hasło (szyfrowane). Płatności przez Stripe.", hosting: "Vercel (USA, standardowe klauzule umowne UE), Supabase (serwery UE), Brevo (Francja), Tawk.to.", cookies: "Tylko technicznie niezbędne pliki cookie." },
  tr: { title: "Gizlilik Politikası", h1: "1. Sorumlu", h2: "2. Veri Toplama", h3: "3. Haklarınız", h4: "4. Hosting", h5: "5. Çerezler", h6: "6. Yasal Dayanak", resp: "Sorumlu: PraxisOnline, Berlinstraße 37, 55411 Bingen am Rhein, Almanya. info@praxisonline.com", rights: "Erişim, düzeltme, silme, işleme kısıtlama, veri taşınabilirliği, itiraz hakkı.", law: "KVKK ve GDPR.", land: "Türkiye", back: "← Geri", data: "İsim (isteğe bağlı), e-posta, şifre (şifreli). Ödemeler Stripe üzerinden.", hosting: "Vercel (ABD, AB standart sözleşme maddeleri), Supabase (AB sunucuları), Brevo (Fransa), Tawk.to.", cookies: "Sadece teknik olarak gerekli çerezler." },
  ja: { title: "プライバシーポリシー", h1: "1. 責任者", h2: "2. データ収集", h3: "3. お客様の権利", h4: "4. ホスティング", h5: "5. Cookie", h6: "6. 法的根拠", resp: "責任者: PraxisOnline, Berlinstraße 37, 55411 Bingen am Rhein, ドイツ. info@praxisonline.com", rights: "アクセス、訂正、消去、処理制限、データポータビリティ、異議申立権（GDPR第15-21条）。", law: "GDPRおよび個人情報保護法。", land: "日本", back: "← 戻る", data: "名前（任意）、メール、パスワード（暗号化）。支払いはStripe経由。", hosting: "Vercel（米国、EU標準契約条項）、Supabase（EUサーバー）、Brevo（フランス）、Tawk.to。", cookies: "技術的に必要なCookieのみ。" },
  zh: { title: "隐私政策", h1: "1. 负责人", h2: "2. 数据收集", h3: "3. 您的权利", h4: "4. 托管", h5: "5. Cookie", h6: "6. 法律依据", resp: "负责人: PraxisOnline, Berlinstraße 37, 55411 Bingen am Rhein, 德国. info@praxisonline.com", rights: "访问、更正、删除、限制处理、数据可携、反对权（GDPR第15-21条）。", law: "GDPR 和《个人信息保护法》。", land: "中国", back: "← 返回", data: "姓名（可选）、电子邮件、密码（加密）。通过Stripe付款。", hosting: "Vercel（美国，欧盟标准合同条款）、Supabase（欧盟服务器）、Brevo（法国）、Tawk.to。", cookies: "仅技术必要的Cookie。" },
    cs: { title: "Zásady ochrany osobních údajů", h1: "1. Správce", h2: "2. Shromažďování údajů", h3: "3. Vaše práva", h4: "4. Hosting", h5: "5. Cookies", h6: "6. Právní základ", resp: "Správce: PraxisOnline, Berlinstraße 37, 55411 Bingen am Rhein, Německo. info@praxisonline.com", rights: "Právo na přístup, opravu, výmaz, omezení, přenositelnost, námitku.", law: "GDPR a zákon o ochraně osobních údajů.", land: "Česká republika", back: "← Zpět", data: "Jméno (volitelné), e-mail, heslo (šifrované). Platby přes Stripe.", hosting: "Vercel (USA, standardní smluvní doložky EU), Supabase (EU), Brevo (FR), Tawk.to.", cookies: "Pouze technicky nezbytné cookies." },
  sk: { title: "Zásady ochrany osobných údajov", h1: "1. Správca", h2: "2. Zhromažďovanie údajov", h3: "3. Vaše práva", h4: "4. Hosting", h5: "5. Cookies", h6: "6. Právny základ", resp: "Správca: PraxisOnline, Berlinstraße 37, 55411 Bingen am Rhein, Nemecko. info@praxisonline.com", rights: "Právo na prístup, opravu, vymazanie, obmedzenie, prenositeľnosť, námietku.", law: "GDPR a zákon o ochrane osobných údajov.", land: "Slovensko", back: "← Späť", data: "Meno (voliteľné), e-mail, heslo (šifrované). Platby cez Stripe.", hosting: "Vercel (USA, štandardné zmluvné doložky EÚ), Supabase (EÚ), Brevo (FR), Tawk.to.", cookies: "Iba technicky nevyhnutné cookies." },
  sl: { title: "Politika zasebnosti", h1: "1. Upravljavec", h2: "2. Zbiranje podatkov", h3: "3. Vaše pravice", h4: "4. Gostovanje", h5: "5. Piškotki", h6: "6. Pravna podlaga", resp: "Upravljavec: PraxisOnline, Berlinstraße 37, 55411 Bingen am Rhein, Nemčija. info@praxisonline.com", rights: "Pravica do dostopa, popravka, izbrisa, omejitve, prenosljivosti, ugovora.", law: "GDPR in ZVOP-2.", land: "Slovenija", back: "← Nazaj", data: "Ime (neobvezno), e-pošta, geslo (šifrirano). Plačila prek Stripe.", hosting: "Vercel (ZDA, standardne pogodbene klavzule EU), Supabase (EU), Brevo (FR), Tawk.to.", cookies: "Samo tehnično potrebni piškotki." },
  sv: { title: "Integritetspolicy", h1: "1. Ansvarig", h2: "2. Datainsamling", h3: "3. Dina rättigheter", h4: "4. Hosting", h5: "5. Cookies", h6: "6. Rättslig grund", resp: "Ansvarig: PraxisOnline, Berlinstraße 37, 55411 Bingen am Rhein, Tyskland. info@praxisonline.com", rights: "Rätt till tillgång, rättelse, radering, begränsning, dataportabilitet, invändning.", law: "GDPR och Dataskyddsförordningen.", land: "Sverige", back: "← Tillbaka", data: "Namn (valfritt), e-post, lösenord (krypterat). Betalningar via Stripe.", hosting: "Vercel (USA, EU-standardavtalsklausuler), Supabase (EU-servrar), Brevo (Frankrike), Tawk.to.", cookies: "Endast tekniskt nödvändiga cookies." },
  no: { title: "Personvernerklæring", h1: "1. Ansvarlig", h2: "2. Datainnsamling", h3: "3. Dine rettigheter", h4: "4. Hosting", h5: "5. Informasjonskapsler", h6: "6. Rettslig grunnlag", resp: "Ansvarlig: PraxisOnline, Berlinstraße 37, 55411 Bingen am Rhein, Tyskland. info@praxisonline.com", rights: "Rett til innsyn, retting, sletting, begrensning, dataportabilitet, protest.", law: "GDPR og Personopplysningsloven.", land: "Norge", back: "← Tilbake", data: "Navn (valgfritt), e-post, passord (kryptert). Betalinger via Stripe.", hosting: "Vercel (USA, EUs standardkontraktsklausuler), Supabase (EU-servere), Brevo (Frankrike), Tawk.to.", cookies: "Kun teknisk nødvendige informasjonskapsler." },
  da: { title: "Privatlivspolitik", h1: "1. Ansvarlig", h2: "2. Dataindsamling", h3: "3. Dine rettigheder", h4: "4. Hosting", h5: "5. Cookies", h6: "6. Retsgrundlag", resp: "Ansvarlig: PraxisOnline, Berlinstraße 37, 55411 Bingen am Rhein, Tyskland. info@praxisonline.com", rights: "Ret til indsigt, berigtigelse, sletning, begrænsning, dataportabilitet, indsigelse.", law: "GDPR og Databeskyttelsesloven.", land: "Danmark", back: "← Tilbage", data: "Navn (valgfrit), e-mail, adgangskode (krypteret). Betalinger via Stripe.", hosting: "Vercel (USA, EU-standardkontraktbestemmelser), Supabase (EU-servere), Brevo (Frankrig), Tawk.to.", cookies: "Kun teknisk nødvendige cookies." },
}

export default function Datenschutz() {
  const [lang, setLang] = useState("de")
  useEffect(() => {
    const stored = localStorage.getItem("lang")
    if (stored && texts[stored]) { setLang(stored); return }
    const browser = (navigator.language || "").split("-")[0]
    if (texts[browser]) { setLang(browser); return }
    setLang("en")
  }, [])
  const t = texts[lang] || texts.en

  return (
    <main className="min-h-screen bg-gradient-to-b from-blue-50 to-white p-4 sm:p-8 max-w-full sm:max-w-3xl mx-auto">
      <div className="bg-white border border-blue-200 shadow-sm rounded-lg sm:rounded-xl p-6 sm:p-10">
        <div className="flex justify-between items-center mb-6">
          <h1 className="text-xl sm:text-2xl sm:text-3xl sm:text-4xl font-bold text-gray-900">{t.title}</h1>
          <span className="text-sm text-gray-400 bg-blue-50 px-3 py-1 rounded-full">{t.land}</span>
        </div>
        <section className="space-y-6 text-lg text-gray-700">
          <div><h2 className="text-xl sm:text-2xl font-semibold text-gray-900 mb-3">{t.h1}</h2><p>{t.resp}</p></div>
          <div><h2 className="text-xl sm:text-2xl font-semibold text-gray-900 mb-3">{t.h2}</h2><p>{t.data}</p></div>
          <div><h2 className="text-xl sm:text-2xl font-semibold text-gray-900 mb-3">{t.h3}</h2><p>{t.rights}</p></div>
          <div><h2 className="text-xl sm:text-2xl font-semibold text-gray-900 mb-3">{t.h4}</h2><p>{t.hosting}</p></div>
          <div><h2 className="text-xl sm:text-2xl font-semibold text-gray-900 mb-3">{t.h5}</h2><p>{t.cookies}</p></div>
          <div><h2 className="text-xl sm:text-2xl font-semibold text-gray-900 mb-3">{t.h6}</h2><p>{t.law}</p></div>
        </section>
      </div>
      <div className="mt-6 text-center"><Link href="/" className="text-[#3B82F6] hover:text-blue-600 underline text-lg">{t.back}</Link></div>
    </main>
  )
}
